# 1. Upstream Backend Cluster
upstream backend_cluster {
    server 127.0.0.1:8081;
    server 127.0.0.1:8082;
}

# 2. Main Traffic Gateway
server {
    listen 80;
    listen [::]:80;

    server_name sitea.local;

    location / {
        proxy_pass http://backend_cluster;

        proxy_set_header Connection "close";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Phase 5 HTTP Security Headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "no-referrer-when-downgrade" always;
    }
}

# 3. Local Backend Node 1
server {
    listen 127.0.0.1:8081;

    root /var/www/node1/html;
    index index.html;
}

# 4. Local Backend Node 2
server {
    listen 127.0.0.1:8082;

    root /var/www/node2/html;
    index index.html;
}
